-- H2 schema aligned with Postgres structure for dev profile
CREATE DOMAIN IF NOT EXISTS status_enum AS VARCHAR(32) CHECK (
  VALUE IN (
    'NEW',
    'PENDING',
    'IN_PROGRESS',
    'COMPLETED',
    'APPROVED',
    'CANCELLED'
  )
);
CREATE TABLE IF NOT EXISTS task (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR(100),
  description VARCHAR(200),
  status status_enum,
  duedate TIMESTAMP(6) WITHOUT TIME ZONE,
  tasknum INTEGER,
  CONSTRAINT tbtask_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_task_status ON task(status);